[project]
name = "learning-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.6.2",
    "nest-asyncio>=1.6.0",
    "notebook>=7.4.4",
    "pyppeteer>=2.0.0",
]
